"""Add Ayurvedic, Patient Statement, Doctor Note, and Attention models

Revision ID: 89a62dceb3f8
Revises: 520b2c19e9b8
Create Date: 2026-10-04 10:54:49.255393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a62dceb3f8'
down_revision: Union[str, Sequence[str], None] = '520b2c19e9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashavidha_pariksha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('prakriti_notes', sa.Text(), nullable=True),
    sa.Column('vikriti_notes', sa.Text(), nullable=True),
    sa.Column('sara', sa.String(), nullable=True),
    sa.Column('sara_notes', sa.Text(), nullable=True),
    sa.Column('samhanana', sa.String(), nullable=True),
    sa.Column('samhanana_notes', sa.Text(), nullable=True),
    sa.Column('pramana', sa.String(), nullable=True),
    sa.Column('pramana_notes', sa.Text(), nullable=True),
    sa.Column('satmya', sa.String(), nullable=True),
    sa.Column('satmya_notes', sa.Text(), nullable=True),
    sa.Column('satva', sa.String(), nullable=True),
    sa.Column('satva_notes', sa.Text(), nullable=True),
    sa.Column('ahara_shakti', sa.String(), nullable=True),
    sa.Column('ahara_shakti_notes', sa.Text(), nullable=True),
    sa.Column('vyayama_shakti', sa.String(), nullable=True),
    sa.Column('vyayama_shakti_notes', sa.Text(), nullable=True),
    sa.Column('vaya', sa.String(), nullable=True),
    sa.Column('vaya_notes', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('physician_confirmed', sa.Boolean(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashavidha_pariksha_id'), 'dashavidha_pariksha', ['id'], unique=False)
    op.create_table('doctor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_notes_id'), 'doctor_notes', ['id'], unique=False)
    op.create_table('patient_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('original_language', sa.String(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('structured_extraction', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_statements_id'), 'patient_statements', ['id'], unique=False)
    op.create_table('prakriti_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('vata_score', sa.Integer(), nullable=True),
    sa.Column('pitta_score', sa.Integer(), nullable=True),
    sa.Column('kapha_score', sa.Integer(), nullable=True),
    sa.Column('dominant_dosha', sa.String(), nullable=True),
    sa.Column('secondary_dosha', sa.String(), nullable=True),
    sa.Column('assessment_method', sa.String(), nullable=True),
    sa.Column('questionnaire_responses', sa.Text(), nullable=True),
    sa.Column('physician_notes', sa.Text(), nullable=True),
    sa.Column('physician_confirmed', sa.Boolean(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prakriti_assessments_id'), 'prakriti_assessments', ['id'], unique=False)
    op.create_table('vikriti_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('vata_imbalance', sa.String(), nullable=True),
    sa.Column('pitta_imbalance', sa.String(), nullable=True),
    sa.Column('kapha_imbalance', sa.String(), nullable=True),
    sa.Column('primary_imbalance', sa.String(), nullable=True),
    sa.Column('agni_status', sa.String(), nullable=True),
    sa.Column('ama_presence', sa.String(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('physician_confirmed', sa.Boolean(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vikriti_assessments_id'), 'vikriti_assessments', ['id'], unique=False)
    op.add_column('chief_complaints', sa.Column('original_text', sa.Text(), nullable=True))
    op.add_column('chief_complaints', sa.Column('original_language', sa.String(), nullable=True))
    op.add_column('chief_complaints', sa.Column('source', sa.String(), nullable=True))
    op.add_column('chief_complaints', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('clinical_sessions', sa.Column(
        'attention_status',
        sa.Enum('ROUTINE', 'NEEDS_ATTENTION', 'PRIORITY', 'CRITICAL', 'FOLLOW_UP', name='attentionstatusenum'),
        nullable=False,
        server_default='ROUTINE',
    ))
    op.add_column('clinical_sessions', sa.Column('attention_reason', sa.Text(), nullable=True))
    op.add_column('clinical_sessions', sa.Column('attention_note', sa.Text(), nullable=True))
    op.add_column('clinical_sessions', sa.Column('attention_changed_by', sa.Integer(), nullable=True))
    op.add_column('clinical_sessions', sa.Column('attention_changed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'clinical_sessions', 'users', ['attention_changed_by'], ['id'])
    op.add_column('hpi', sa.Column('source', sa.String(), nullable=True))
    op.add_column('medication_histories', sa.Column('source', sa.String(), nullable=True))
    op.add_column('medication_histories', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('medication_histories', sa.Column('requires_verification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_histories', 'requires_verification')
    op.drop_column('medication_histories', 'ai_confidence')
    op.drop_column('medication_histories', 'source')
    op.drop_column('hpi', 'source')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'clinical_sessions', type_='foreignkey')
    op.drop_column('clinical_sessions', 'attention_changed_at')
    op.drop_column('clinical_sessions', 'attention_changed_by')
    op.drop_column('clinical_sessions', 'attention_note')
    op.drop_column('clinical_sessions', 'attention_reason')
    op.drop_column('clinical_sessions', 'attention_status')
    op.drop_column('chief_complaints', 'ai_confidence')
    op.drop_column('chief_complaints', 'source')
    op.drop_column('chief_complaints', 'original_language')
    op.drop_column('chief_complaints', 'original_text')
    op.drop_index(op.f('ix_vikriti_assessments_id'), table_name='vikriti_assessments')
    op.drop_table('vikriti_assessments')
    op.drop_index(op.f('ix_prakriti_assessments_id'), table_name='prakriti_assessments')
    op.drop_table('prakriti_assessments')
    op.drop_index(op.f('ix_patient_statements_id'), table_name='patient_statements')
    op.drop_table('patient_statements')
    op.drop_index(op.f('ix_doctor_notes_id'), table_name='doctor_notes')
    op.drop_table('doctor_notes')
    op.drop_index(op.f('ix_dashavidha_pariksha_id'), table_name='dashavidha_pariksha')
    op.drop_table('dashavidha_pariksha')
    sa.Enum(name='attentionstatusenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
